### ISSUE TITLE
Invalid OCI Helm chart 

### ISSUE THREAD

**Issue by g-bohncke** [updatecli/updatecli#1968] opened 2024-02-29 21:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running  updatecli apply  --config manifest.yaml --experimental

with: manifest.yaml 
sources:
  lastMinorRelease:
    kind: helmchart
    spec:
      url: "oci://public.ecr.aws/karpenter"
      name: "karpenter"
      version: "v0.*.*"

will result in the following error:

ERROR: ✗ invalid OCI Helm chart public.ecr.aws\karpenter\karpenter: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: public.ecr.aws\karpenter\karpenter
ERROR: { ✗   { {  } }   ERROR: ✗ invalid OCI Helm chart public.ecr.aws\karpenter\karpenter: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: public.ecr.aws\karpenter\karpenter
} invalid OCI Helm chart public.ecr.aws\karpenter\karpenter: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: public.ecr.aws\karpenter\karpenter
Pipeline "MANIFEST.YAML" failed
Skipping due to:
        sources stage:  "invalid OCI Helm chart public.ecr.aws\\karpenter\\karpenter: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: public.ecr.aws\\karpenter\\karpenter"

### Expected Behavior

For it so correctly pull the version information

### Environment

```markdown
- OS: windows
- updatecli:  0.73.0
```

### Anything else?

Looks like a similar bug reported here:
https://github.com/GoogleContainerTools/kaniko/issues/1789

this issue talks about I.e. by using name.NewRepository(...) instead of name.NewRegistry(...) and it seems  NewRepository is used https://github.com/updatecli/updatecli/blob/706ca7d2846dc56f5c20012f65ab99a33abddfb8/pkg/plugins/resources/helm/source_oci.go#L19C20-L19C33

**Comment by OcamsRazor** [comment] 2024-03-08 11:05
I also have issues with Karpenter. 
As a workaround I have tried explicitly setting 
```
versionFilter:
  kind: semver
```
This results in error `manifest does not contain minimum number of descriptors (2), descriptors found: 1"` because of `✔ OCI version "20221219" found matching pattern "*"`

Adding `pattern: < 100` will skip the CalVers and give you the actual latest release.

---
I have also tried to workaround with a regex filter but the list of tags retrieved from `oci://public.ecr.aws/karpenter` does not seem to be sorted so that doesn't work at all.

```
versionfilter:
  kind: regex
  pattern: "^v?\\d+\\.\\d+\\.\\d+$"
```

**Comment by olblak** [comment] 2024-03-09 20:35
@OcamsRazor 

By default, in Updatecli `semver` accepts version like `1`, or `1.0` and consider it as `1.0.0` so in this case it considers `20221219` as `20221219.0.0`

If you are only interested by "strict" semantic versioning you can use the `strict` parameter like in the following example

```
sources:
  lastMinorRelease:
    kind: helmchart
    spec:
      url: "oci://public.ecr.aws/karpenter"
      name: "karpenter"
      versionfilter:
        kind: semver
        strict: true
```

<details><summary>Console Output</summary>

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "/tmp/updatecli.yaml"

SCM repository retrieved: 0


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



##################
# UPDATECLI.YAML #
##################


SOURCES
=======

lastMinorRelease
----------------
Searching for version matching pattern "*"
✔ OCI version "0.35.1" found matching pattern "*"

=============================

REPORTS:



- UPDATECLI.YAML:
	Source:
		✔ [lastMinorRelease] 

Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	0
  * Skipped:	1
  * Succeeded:	0
  * Total:	1
```

</details>

> I have also tried to workaround with a regex filter but the list of tags retrieved from oci://public.ecr.aws/karpenter does not seem to be sorted so that doesn't work at all.

I am not familiar with ecr by I can tell you that different OCI registries sort version in a different way like ghcr.io and dockerhub won't return the same list even if the same image is published to both location at the same time (like Updatecli does)

**Comment by olblak** [comment] 2024-03-09 20:37
@g-bohncke Unfortunately I can't reproduce your issue with Updatecli 0.74.0 

Also you example is formatted correctly, you can add ``` before and after your code snippet.

Maybe my previous comment answer the problem

**Comment by olblak** [comment] 2024-03-09 20:41
Also @OcamsRazor the --experimental is not needed in your example. Maybe I forgot to update some documentation that suggest that --experimental is needed

**Comment by olblak** [comment] 2024-03-09 20:43
Or maybe you are facing a windows issue 🤔

**Comment by OcamsRazor** [comment] 2024-03-12 11:04
> If you are only interested by "strict" semantic versioning you can use the `strict` parameter like in the following example It will ignore version not matching semantic versioning definition like `1` or `1.0`

The chart has apparently started following strict semantic versioning since 0.35.0 which was released just 2 weeks ago.
Up until then version where prefixed with `v` and would have been ignored with `strict: true` (don't think transformers would be usable in this stage?). 
Anyway, now `strict: true` will be indeed be cleaner than my workaround. 

> I am not familiar with ecr by I can tell you that different OCI registries sort version in a different way like ghcr.io and dockerhub won't return the same list even if the same image is published to both location at the same time (like Updatecli does)

That's what I thought and would be hard to implement without a standard format..

Thanks for the suggestions!

**Comment by olblak** [comment] 2024-03-15 20:06
> The chart has apparently started following strict semantic versioning since 0.35.0 which was released just 2 weeks ago.
Up until then version where prefixed with v and would have been ignored with strict: true (don't think transformers would be usable in this stage?).
Anyway, now strict: true will be indeed be cleaner than my workaround.

You are right regarding the transformers has it applies to the source output.

I thought Helm chart stored on OCI registry required semantic versioning. 
Worst case scenario we could fallback to the dockerimage plugin like in the following example .
The dockerimage has the specific parameter `tagfilter` to pre-filter the list of tag retrieved from the API because the versioning practice in the docker ecosystem is a real mess :)

```
sources:
  lastMinorRelease:
    kind: dockerimage
    spec:
      image: "public.ecr.aws/karpenter/karpenter"
      tagfilter: 'v(\d*).(\d*).(\d*)'
      name: "karpenter"
      versionfilter:
        kind: semver
        pattern: <0.34.0
```

The Updatecli "dockerimage" plugin is OCI compliant so it can retrieve version from an OCI artifact including helm artifact.
For example updatecli policies can be stored on any OCI registry like dockerhub or ghcr.io
I opened an issue to better highlight that. https://github.com/updatecli/updatecli/issues/1709

**Comment by olblak** [comment] 2024-03-15 20:07
@g-bohncke  @OcamsRazor I am now closing this issue as I can't reproduce. 
Feel free to reopen if my workaround are not sufficient.

**Closed by olblak** 2024-03-15 20:07 UTC
Labels: bug
