### ISSUE TITLE
updatecli generates notification spam in latest v0.48 release

### ISSUE THREAD

**Issue by jetersen** [updatecli/updatecli#1252] opened 2023-03-29 07:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems like updatecli v0.48 is a bad release with lots of notification spam.

![image](https://user-images.githubusercontent.com/1661688/228462446-64eb0942-94a8-43c3-aabc-e908dd4a3bb6.png)

### Environment

```markdown
- updatecli: v0.48.0
```

**Comment by olblak** [comment] 2023-03-29 08:29
Thanks for the reporting, I noticed exactly the same behavior on https://github.com/updatecli/website/pulls?q=is%3Apr+is%3Aclosed but I only noticed it there... so I stopped my investigation when the problem was resolved :( 

The weird thing is, the targeted branch was already up to date (after the first PR merge), so all the following pullrequest were totally wrong. It appears that the pullrequest merge would just push empty commit such as https://github.com/updatecli/website/commit/9740675c921759199ce3e5abb554173953e4c59c

It stopped behaving like that when I deleted manually the branch even though that repository is configured to delete the branch when the pullrequest is merged so I really didn't understand...

My intial assumption was something wrong happened on the Github side a that time.

Outside of a problem on GitHub, the only change in the last Updatecli release that could lead to this issue would come from this go-git release https://github.com/go-git/go-git/releases/tag/v5.6.1
I

**Comment by olblak** [comment] 2023-03-29 08:38
Interestingly enough, I tried to manually open this pullrequest 

https://github.com/updatecli/updatecli-action/compare/updatecli:v2...updatecli:updatecli_f1d125f2e8197c29b4655c467651503ab61377fa1a31af6152254a7e8764c2ab?expand=1

It complains that I can open more than 100 PR which is a nice safeguard 

![image](https://user-images.githubusercontent.com/2360224/228475853-2971dc0f-eadf-434d-8866-8edc26f7790e.png)

More importantly it shows me that it want to update the file, even though the file is already up to date

![image](https://user-images.githubusercontent.com/2360224/228476304-de4ff842-c75d-4f91-a8f0-fe6b0a54c2ca.png)

as per said

![image](https://user-images.githubusercontent.com/2360224/228476479-c3ff7888-577e-4497-af6b-58bf6297a0c8.png)

**Comment by olblak** [comment] 2023-03-29 08:38
This makes me thing that the problem is on GitHub side

**Comment by olblak** [comment] 2023-03-29 08:48
It appears the Updatecli version used on updatecli/updatecli-action is an older one https://github.com/updatecli/updatecli-action/blob/c23f672e8ba3e27e073a2ec64488f7001a20f74b/.github/workflows/updatecli.yaml#L26

which makes me thing of a GitHub issue

**Comment by olblak** [comment] 2023-03-29 08:49
![image](https://user-images.githubusercontent.com/2360224/228479792-8c09d862-c917-44fb-a824-6efbf094d94c.png)

**Comment by v1v** [comment] 2023-03-30 07:15
> More importantly it shows me that it want to update the file, even though the file is already up to date

That's a similar behaviour we have noticed too:

- https://github.com/elastic/opbeans-python/pull/222/files
- https://github.com/elastic/opbeans-python/pull/220/files

using `Application:	0.44.2`, https://github.com/elastic/opbeans-python/actions/runs/4457071184/jobs/7827922745#step:3:244

In case it helps

**Comment by olblak** [comment] 2023-03-30 07:15
After additional testing, Apparently it's now possible to open several pullrequest with exactly the same content. 

- https://github.com/olblak/fleet-lab/pull/59/files
- https://github.com/olblak/fleet-lab/pull/60/files

**Comment by olblak** [comment] 2023-03-30 08:53
> > More importantly it shows me that it want to update the file, even though the file is already up to date
> 
> That's a similar behaviour we have noticed too:
> 
>     * https://github.com/elastic/opbeans-python/pull/222/files
> 
>     * https://github.com/elastic/opbeans-python/pull/220/files
> 
> 
> using `Application: 0.44.2`, https://github.com/elastic/opbeans-python/actions/runs/4457071184/jobs/7827922745#step:3:244
> 
> In case it helps

Thanks @v1v 
You confirm that the problem isn't introduce in v0.48.0.

Github pullrequest looks totally foo bar and I don't know if it's the new normal :( 

The updatecli/website is configured to delete head branch once the pullrequest is merged which is not done.
Also it appears that we can now re-open pullrequest even though it was already merge, if we merge it, then Updatecli create empty commits as the change was already merged in a previous pullrequest

I think the best for now is to disable the auto-merge pullrequest :(

**Comment by olblak** [comment] 2023-03-30 08:59
The situation seems to be back to normal, I can't manually create multiple pullrequest anymore 

![image](https://user-images.githubusercontent.com/2360224/228785117-f036fb29-13bf-4ca8-b4b3-1eeea951abea.png)

**Comment by olblak** [comment] 2023-03-31 07:03
Well I am considering creating a new release that disable the auto-merge feature for now

**Comment by olblak** [comment] 2023-04-03 19:23
What seems to have work on my repository is closing open PR, manually deleting branches from the UI, and then it seems  be fine

**Comment by olblak** [comment] 2023-04-07 19:28
The problem seems to be gone now. 
The last part where I see this issue occurring, it was resolved after manually closing the PR, and deleting the branch

**Closed by olblak** 2023-04-07 19:28 UTC
Labels: bug
