### ISSUE TITLE
`body` parameter ignored with GitLab merge requests

### ISSUE THREAD

**Issue by tiehfood** [updatecli/updatecli#1531] opened 2023-08-24 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

body parameter is ignored in the created merge request

### Expected Behavior

body parameter should override default body of merge request

### Environment

```markdown
- updatecli: 0.57.0
```

**Comment by olblak** [comment] 2023-08-24 14:59
🤔  It should be working https://github.com/updatecli/updatecli/blob/6293758fb602fc06dcfa665017267bb4c87eeff8/pkg/plugins/resources/gitlab/mergerequest/create.go#L30

**Comment by tiehfood** [comment] 2023-08-24 16:30
Yeah, I also checked the code and saw that snippet. But I had no luck setting it to my custom body. It always put the default body in the MR

**Comment by tiehfood** [comment] 2023-08-25 05:54
It seems like all spec definitions of the gitlab merge request are ignored

**Comment by olblak** [comment] 2023-08-25 07:33
I had a look at the code, and I spot an few things.

This line is wrong https://github.com/updatecli/updatecli/blob/6293758fb602fc06dcfa665017267bb4c87eeff8/pkg/plugins/resources/gitlab/mergerequest/create.go#L24 

And it should be `utils.GeneratePullRequestBody(g.spec.Body, report.ToActionsString())`

I need to setup my gitlab environment to reproduce the issue, because running `go build -o bin/updatecli . &&  ./bin/updatecli apply --config e2e/updatecli.d/success.d/gitlab/scm.yaml --push=false --clean=true ` won't execute the part of the code that interest us

**Comment by olblak** [comment] 2023-08-25 09:16
I think found the root cause of the problem.

I am using the library drone/go-scm to handle the GitLab interaction and it appears that the mergequest uses URL value https://github.com/drone/go-scm/blob/1579795501b0ae415d6f75594751ffe3ddcaeb76/scm/driver/gitlab/pr.go#L63 to configure the pullrequest which has a limit on the number of character  as explained on https://docs.gitlab.com/ee/api/rest/#request-payload

That library was great to bootstrap the GitLab plugin but I think, I'll need to refactor the plugin.

**Comment by olblak** [comment] 2023-08-25 09:38
For info to validate that the body is working for me, I used 

<details><summary>manifest.yaml</summary>

```
name: Test GitLab scm 

scms:
  gitlab:
    kind: gitlab
    spec:
      owner: "olblak"
      repository: "updatecli"
      branch: main
      username: '{{ requiredEnv "UPDATECLI_GITLAB_ACTOR" }}'
      token: '{{ requiredEnv "UPDATECLI_GITLAB_TOKEN" }}'

sources:
  license:
    name: Retrieve license file content
    kind: file
    scmid: gitlab
    spec:
      file: LICENSE
  readme:
    name: Retrieve readme file content
    kind: file
    scmid: gitlab
    spec:
      file: README.adoc

targets:
  readme:
    name: Update README license file content
    kind: file
    sourceid: readme
    transformers:
      - addprefix: "xx"
    scmid: gitlab
    spec:
      file: README.adoc

actions:
  default:
    title: Bump xxx 
    kind: gitlab/mergerequest
    scmid: gitlab
    spec:
      body: My awesome custom body
```
</details>

which created this mergerequest with the correct description https://gitlab.com/olblak/updatecli/-/merge_requests/1224

But if I remove `body: My awesome custom body` then I face the problem mentioned in my previous comment, the description become too big to be passed by url value

**Comment by tiehfood** [comment] 2023-08-25 10:53
Very strange, it seems to work now, after I recreated my config... Nevertheless, thanks for your support 👍

**Comment by olblak** [comment] 2023-08-25 15:07
If you use an IDE that support jsonschema store such as Intellij/NeoVim (with the right plugin), or Vscode then you can leverage schema validation for your manifest(s) if they live under the directory `updatecli.d`

While debugging this issue, I noticed that the schema mentioned some fields as required even though they were not such as owner/repository, I opened  https://github.com/updatecli/updatecli/pull/1537 to fix that 

Once the PR is merge we'll need to wait +-10min for the new schema to be generate and automatically published on https://www.updatecli.io/schema/latest/config.json 

![image](https://github.com/updatecli/updatecli/assets/2360224/37da6304-8d6b-4c41-ba6d-d1817d3441e9)

This helps to debug typos in params

**Comment by olblak** [comment] 2023-08-27 07:20
I am closing this issue as we couldn't reproduce the problem and it seems to be resolved now.
I open https://github.com/updatecli/updatecli/issues/1540 to track the mergrequest too large problem

**Closed by olblak** 2023-08-27 07:20 UTC
Labels: bug, scm-gitlab
