### ISSUE TITLE
Unicode characters aren't correctly rendered on Windows

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#408] opened 2021-12-10 10:12 UTC
**Describe the bug**

Some characters aren't correctly rendered on Windows:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/91831478/145556884-610fb6b9-bd86-4e39-b16d-69ef85c35894.png">

**Steps to Reproduce**
Run `updatecli diff` on Windows

**Expected behavior**

All characters are correctly rendered.
**Version**

- OS: Windows
- Updatecli version: 0.16.1

cc @smerle33

**Comment by dduportal** [comment] 2022-01-30 12:57
Sounds related to the windows CMD and not updatecli:

- https://stackoverflow.com/questions/28413489/using-box-drawing-unicode-characters-in-batch-files/28426204#28426204
- https://stackoverflow.com/questions/36040704/unicode-symbols-in-a-batch-file


Closing as it's not a bug: updatecli's output is UTF-8, there nothing we can do if command line does not support it (unless I'm mistaken).

**Closed by dduportal** 2022-01-30 12:57 UTC
Labels: bug
