### ISSUE TITLE
updatecli is messing with indents 😓

### ISSUE THREAD

**Issue by jetersen** [updatecli/updatecli#89] opened 2020-08-18 12:38 UTC
**Describe the bug**
after a `updatecli apply` it messes with indents on a list.

**To Reproduce**

`updatecli.d/argocd.tpl`
```yaml
source:
  kind: githubRelease
  spec:
    owner: "argoproj"
    repository: "argo-cd"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.user }}"
    version: "latest"
targets:
  argocd:
    name: argo-cd
    kind: yaml
    prefix: https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=
    spec:
      file: argocd/kustomization.yaml
      key: bases[0]
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "owner"
        repository: "repo"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "master"
```
`argocd/kustomization.yaml`
```yaml
bases:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1
resources:
- certificate.yaml
- argocd-ingress-webhook.yaml
- appprojects/core-services.yaml
- appprojects/env-proxy.yaml
- appprojects/system-services.yaml
patches:
- argocd-service.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml
```

**Expected behavior**
only the bases line is updated without touching indents as we are trying to follow a style.

**Screenshots**
![image](https://user-images.githubusercontent.com/1661688/90513316-b9965000-e15f-11ea-8644-6254b81598ae.png)

**Version (please complete the following information):**
 - OS: linux
 - Version v0.0.20

**Comment by olblak** [comment] 2020-08-20 16:49
Indeed lists are aligned with the key, this is the default behavior from [go-yaml/yaml](https://github.com/go-yaml/yaml/issues/647) the yaml library.
Regarding indentation, at the moment, it's set to 2 but we could easily modify the code to provides it as an option in the yaml spec.

**Comment by olblak** [comment] 2020-08-20 16:50
ha apparently in your case it's the opposite happening here, let me look, I am wondering if the problem is not coming from  the SetIndent

**Comment by olblak** [comment] 2021-09-23 08:52
I am closing this ticket as this is the default behavior for the YAML library that we are using. Feel free to reopen in the future, if a better solution exists.

**Closed by olblak** 2021-09-23 08:52 UTC
Labels: bug
